log:
  loglevel: info
dns:
  servers:
  - https+local://8.8.8.8/dns-query
inbounds:
- port: 8080
  protocol: trojan
  settings:
    clients:
    - password: "dfd2521f-334c-4040-9d25-cdfc8fe0d10d"
  streamSettings:
    network: ws
    wsSettings:
      path: qwe
  sniffing:
    enabled: false
    destOverride:
    - http
    - tls
    - quic
outbounds:
- protocol: freedom
  tag: direct
  settings:
    domainStrategy: UseIPv4
